---
baseURL: "http://example.org/"
title: "Calvary Temple"
languageCode: "en-us"
theme: "calvary"
menu:
  main:
  - Name: Give
    URL: https://calvarytemple.churchcenteronline.com/giving?open-in-church-center-modal=true
    Identifier: Give
    Weight: 300
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  livestream: 
    enabled: true
    youtube_id: calvarytemple9808
  imageCDN: "https://cdn.thecalvarytemple.org/static/images/"
  sassCDN: "https://cdn.thecalvarytemple.org/static/sass/"
resources:
  sources:
    - src: "content/**"
      exclude: ["**/index.md"]

module:
  mounts:
    - source: themes/calvary/assets/sass
      target: assets/sass
    - source: themes/calvary/static
      target: static
    - source: themes/calvary/assets/js
      target: assets/js
    - source: themes/calvary/layouts
      target: layouts
    - source: layouts
      target: layouts
    - source: content
      target: content
    - source: layouts/shortcodes
      target: layouts/shortcodes

# Hugo's asset pipeline configuration
minify:
  minifyOutput: true

build:
  writeStats: true

security:
  enableInlineShortcodes: true

outputs:
  home: ["HTML", "RSS"]
  section: ["HTML", "RSS"]
  taxonomyTerm: ["HTML"]
  taxonomy: ["HTML"]
  term: ["HTML"]
---
