backend:
  name: github
  branch: main
  repo: thecalvarytemple/website
  client_id: 'Ov23liA2teaycARJnQgO'
  base_url: 'https://thecalvarytemple.org'
  auth_endpoint: /api/auth
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "readings"
    label: "Bible Reading"
    folder: "content/readings"
    create: true
    slug: "{{title}}"
    identifier_field: date
    fields:
      - { label: 'Title', name: 'title', widget: 'string', hint: 'Month of Year' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', hint: 'Date in Month' }
      - { label: 'Order of Month', name: 'weight', widget: 'number', hint: 'What is the numerical number of the Month' }
      - { label: 'Header', name: 'header', widget: 'string', hint: 'This should stay bible.jpg' }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'This is where the list will go for each day of the bible reading plan' }
  - name: "messages"
    label: Messages
    label_singular: 'Message'
    folder: content/messages
    create: true
    slug: "{{title}}"
    nested:
      depth: 2
      summary: '{{path}}'
    fields:
      - label: "Date"
        name: "date"
        widget: "datetime"
        hint: "The date on which the message was delivered. Format = 2024-12-01T09:00:00-08:00"
        required: true
      - label: "Series"
        name: "series"
        widget: "string"
        hint: "The series to which the message belongs. Use all lower case and replace spaces with dashes. Must match the first part of the Path field (before the slash)! Example: chaos"
        required: true
      - label: "Speaker"
        name: "speaker"
        widget: "string"
        hint: "The speaker who delivered the message. Example: Scott Mays"
        required: true
      - label: "Podcast URL"
        name: "podcast"
        widget: "string"
        hint: "The filename to the MP3/M4A file containing the podcast's audio. Example: loving-like-jesus-part-1.mp3 or chaos.m4a"
        required: true
      - label: "Podcast size (bytes)"
        name: "podcast_bytes"
        widget: "number"
        hint: "The size of the MP3 file in bytes. Example: 20938922"
        value_type: "int"
        required: true
      - label: "Podcast duration (MM:SS)"
        name: "podcast_duration"
        widget: "string"
        hint: "The duration of the audio file. Example: 45:32"
        pattern: ['[0-9]+:[0-9]+', "Format as MM:SS"]
        required: true
      - label: "YouTube ID"
        name: "youtube_id"
        widget: "string"
        hint: "The YouTube ID of the video version of the podcast; this is the part of the YouTube URL after the v= and before the & (if any). Example: dQw4w9WgXcQ"
        pattern: ['.{11,}', "Must have at least 11 characters"]
        required: true
      - label: "Type"
        name: "type"
        widget: "hidden"
        default: "message"
      - label: Title
        name: title
        widget: string
        hint: "The title of the message. Example: Loving Like Jesus Loved His Disciples"
        required: true
      - label: Body
        name: body
        widget: markdown
        required: true
        hint: "A description/summary of the message. Example: From Psalms 72, Pastor Scott demonstrates the three ways... "
    meta: { path: { widget: string, label: 'Path', index_file: 'index', hint: "The series, a slash, and then a short title with only letters and numbers (no spaces). Example: loving-like-jesus/part-1" } }

